# Generated by Django 4.0.6 on 2022-07-27 12:39
import random
import names
from django.db import migrations


STD_SALARY = 100  # dollars will be modified depending on team role


def populate_employee(apps, schema_editor):
    Employee = apps.get_model('catalogue', 'Employee')

    for i in range(42000):
        Employee.objects.create(role='JNR',
                                first_name=names.get_first_name(),
                                last_name=names.get_last_name(),
                                age=random.randint(18, 60),
                                salary=STD_SALARY * random.randint(9, 12))
    for i in range(7000):
        Employee.objects.create(role='MDL',
                                first_name=names.get_first_name(),
                                last_name=names.get_last_name(),
                                age=random.randint(18, 60),
                                salary=STD_SALARY * random.randint(14, 17))
    for i in range(1000):
        Employee.objects.create(role='SNR',
                                first_name=names.get_first_name(),
                                last_name=names.get_last_name(),
                                age=random.randint(18, 60),
                                salary=STD_SALARY * random.randint(18, 22))
    for i in range(200):
        Employee.objects.create(role='TML',
                                first_name=names.get_first_name(),
                                last_name=names.get_last_name(),
                                age=random.randint(18, 60),
                                salary=STD_SALARY * random.randint(25, 30))
    for i in range(30):
        Employee.objects.create(role='MNG',
                                first_name=names.get_first_name(),
                                last_name=names.get_last_name(),
                                age=random.randint(18, 60),
                                salary=STD_SALARY * random.randint(40, 50))


class Migration(migrations.Migration):
    dependencies = [
        ('catalogue', '0002_employee_employment_date_employee_manager_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_employee)
    ]
