# Generated by Django 4.0.6 on 2022-08-01 20:00

from django.db import migrations


def populate_slugs(apps, schema_editor):
    Employee = apps.get_model('catalogue', 'Employee')
    all_employees = Employee.objects.all()
    for employee in all_employees:
        employee.slug = f'{employee.last_name} {employee.first_name}-{employee.pk}'
        employee.save()


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_alter_employee_slug'),
    ]

    operations = [
        migrations.RunPython(populate_slugs)
    ]
